### ISSUE TITLE
🛠️ Refactoring: 모임 > 메인 화면 

### ISSUE THREAD

**Issue by slr-09** [KUIT-CoNet/CoNet-iOS#31]
### Descrpiton
모임을 들어갔을 때 메인 화면을 리팩토링합니다. 

### Todo
- [x] 모임 정보 (이미지, 이름, 인원 등)
- [x] 캘린더 
- [x] 특정 날짜의 약속
- [x] 대기 중 약속 기능 삭제

### Information / ETC
- 긴급도: `High` (High/Mid/Low로 적어주세요!)
- 예상 소요 시간: `2h+` (시간은 h, 하루 이상 걸린다면 d!)
