### ISSUE TITLE
🛠️ Refactoring: 홈탭

### ISSUE THREAD

**Issue by slr-09** [KUIT-CoNet/CoNet-iOS#4]
### Descrpiton
홈탭 전체를 리팩토링합니다. 

### Todo
- [x] 캘린더 day 리팩토링
- [x] 캘린더 month 이동 리팩토링
- [x] 오늘의 약속 리팩토링
- [x] 대기 중 약속 리팩토링

### Information / ETC
- 긴급도: `High` (High/Mid/Low로 적어주세요!)
- 예상 소요 시간: `3d+` (시간은 h, 하루 이상 걸린다면 d!)

**Comment by anjiniii** [comment]
디스코드에 댓글도 가는지 테스트에용
