### ISSUE TITLE
🛠️ Refactoring: 초대 코드 팝업 구현 후, 관련 내용 적용 및 리팩토링

### ISSUE THREAD

**Issue by anjiniii** [KUIT-CoNet/CoNet-iOS#54]
### Descrpiton
초대 코드 팝업이 두 군데(코드 입력, 코드 공유)에서 사용되고 있더라구요!
그래서 이 팝업을 컴포넌트로 만들고, 두 곳에서 공유할 수 있도록 하려고 합니다.

### Todo
- [x] 초대 코드 팝업
- [x] 코드 공유 VC에 적용 및 리팩토링
- [ ] 코드 입력 VC에 적용

### Information / ETC
- 긴급도: `High` (High/Mid/Low로 적어주세요!)
- 예상 소요 시간: `2h+` (시간은 h, 하루 이상 걸린다면 d!)
